---
kind: pipeline
type: docker
name: lint-test

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: phoenix

steps:
- name: npm-install
  pull: always
  image: owncloudci/php:7.1
  commands:
  - yarn install

- name: lint-test
  pull: always
  image: owncloudci/php:7.1
  commands:
  - yarn run lint

trigger:
  ref:
  - refs/tags/**
  - refs/pull/**
  - refs/pull-requests/**
  - refs/merge-requests/**
  - refs/heads/master
  - refs/heads/release*
  - refs/heads/develop*

---
kind: pipeline
type: docker
name: Rename-Trash-Files-IE11

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: phoenix

steps:
- name: npm-install
  pull: always
  image: owncloudci/php:7.1
  commands:
  - yarn install

- name: build-phoenix
  pull: always
  image: owncloudci/php:7.1
  commands:
  - yarn dist
  - cp tests/drone/config.json dist/config.json

- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    version: daily-master-qa

- name: clone-oauth
  pull: always
  image: owncloudci/php:7.1
  commands:
  - git clone -b master https://github.com/owncloud/oauth2.git /var/www/owncloud/server/apps/oauth2
  - cd /var/www/owncloud/server/apps/oauth2
  - make vendor

- name: setup-server-phoenix
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server/
  - php occ a:e testing
  - php occ config:system:set trusted_domains 1 --value=owncloud
  - php occ config:system:set cors.allowed-domains 0 --value=http://phoenix
  - php occ log:manage --level 2
  - php occ config:list
  - php occ a:e oauth2
  - php occ oauth2:add-client Phoenix Cxfj9F9ZZWQbQZps1E1M0BszMz6OOFq3lxjSuc8Uh4HLEYb9KIfyRMmgY5ibXXrU 930C6aA0U1VhM03IfNiheR2EwSzRi4hRSpcNqIhhbpeSGU6h38xssVfNcGP0sSwQ http://phoenix/oidc-callback.html
  - php occ config:system:set skeletondirectory --value=/var/www/owncloud/server/apps/testing/data/webUISkeleton
  - php occ config:system:set dav.enable.tech_preview  --type=boolean --value=true
  - php occ config:system:set phoenix.baseUrl --value="http://phoenix"
  - php occ config:system:set sharing.federation.allowHttpFallback --value=true --type=bool

- name: owncloud-log
  pull: always
  image: owncloud/ubuntu:16.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - chown www-data * -R

- name: copy-files-for-upload
  pull: always
  image: owncloudci/php:7.1
  commands:
  - ls -la /filesForUpload
  - cp -a /var/www/owncloud/phoenix/tests/acceptance/filesForUpload/. /filesForUpload
  - ls -la /filesForUpload
  volumes:
  - name: uploads
    path: /filesForUpload

- name: webui-acceptance-tests
  pull: always
  image: owncloudci/nodejs:11
  commands:
  - cd /var/www/owncloud/phoenix
  - curl http://phoenix/oidc-callback.html
  - yarn run acceptance-tests-drone
  environment:
    BACKEND_HOST: http://owncloud
    BROWSER_NAME: internet explorer
    SAUCELABS_TUNNEL_NAME: ${DRONE_BUILD_NUMBER}-acceptance-Rename-Trash-Files-IE11
    SAUCE_ACCESS_KEY:
      from_secret: sauce_access_key
    SAUCE_USERNAME:
      from_secret: sauce_username
    SELENIUM_HOST: saucelabs
    SELENIUM_PORT: 4445
    SERVER_HOST: http://phoenix
    TEST_CONTEXT: webUI[R,T,F]*
    TEST_TAGS: "@smokeTest and not @skip and not @skipOnIE"

services:
- name: phoenix
  pull: always
  image: owncloudci/php:7.1
  commands:
  - mkdir dist
  - /usr/local/bin/apachectl -e debug -D FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/phoenix/dist

- name: owncloud
  pull: always
  image: owncloudci/php:7.1
  command:
  - /usr/local/bin/apachectl
  - -e
  - debug
  - -D
  - FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server/

- name: saucelabs
  pull: if-not-exists
  image: henrrich/docker-sauce-connect:latest
  commands:
  - /usr/local/sauce-connect/bin/sc -i ${DRONE_BUILD_NUMBER}-acceptance-Rename-Trash-Files-IE11
  environment:
    SAUCE_ACCESS_KEY:
      from_secret: sauce_access_key
    SAUCE_USERNAME:
      from_secret: sauce_username

- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

volumes:
- name: uploads
  temp: {}

trigger:
  ref:
  - refs/tags/**
  - refs/pull/**
  - refs/pull-requests/**
  - refs/merge-requests/**
  - refs/heads/master
  - refs/heads/release*
  - refs/heads/develop*

depends_on:
- lint-test

---
kind: pipeline
type: docker
name: Sharing-IE11

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: phoenix

steps:
- name: npm-install
  pull: always
  image: owncloudci/php:7.1
  commands:
  - yarn install

- name: build-phoenix
  pull: always
  image: owncloudci/php:7.1
  commands:
  - yarn dist
  - cp tests/drone/config.json dist/config.json

- name: install-core
  pull: always
  image: owncloudci/core
  settings:
    core_path: /var/www/owncloud/server
    db_host: mysql
    db_name: owncloud
    db_password: owncloud
    db_type: mysql
    db_username: owncloud
    version: daily-master-qa

- name: clone-oauth
  pull: always
  image: owncloudci/php:7.1
  commands:
  - git clone -b master https://github.com/owncloud/oauth2.git /var/www/owncloud/server/apps/oauth2
  - cd /var/www/owncloud/server/apps/oauth2
  - make vendor

- name: setup-server-phoenix
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server/
  - php occ a:e testing
  - php occ config:system:set trusted_domains 1 --value=owncloud
  - php occ config:system:set cors.allowed-domains 0 --value=http://phoenix
  - php occ log:manage --level 2
  - php occ config:list
  - php occ a:e oauth2
  - php occ oauth2:add-client Phoenix Cxfj9F9ZZWQbQZps1E1M0BszMz6OOFq3lxjSuc8Uh4HLEYb9KIfyRMmgY5ibXXrU 930C6aA0U1VhM03IfNiheR2EwSzRi4hRSpcNqIhhbpeSGU6h38xssVfNcGP0sSwQ http://phoenix/oidc-callback.html
  - php occ config:system:set skeletondirectory --value=/var/www/owncloud/server/apps/testing/data/webUISkeleton
  - php occ config:system:set dav.enable.tech_preview  --type=boolean --value=true
  - php occ config:system:set phoenix.baseUrl --value="http://phoenix"
  - php occ config:system:set sharing.federation.allowHttpFallback --value=true --type=bool

- name: owncloud-log
  pull: always
  image: owncloud/ubuntu:16.04
  detach: true
  commands:
  - tail -f /var/www/owncloud/server/data/owncloud.log

- name: fix-permissions
  pull: always
  image: owncloudci/php:7.1
  commands:
  - cd /var/www/owncloud/server
  - chown www-data * -R

- name: copy-files-for-upload
  pull: always
  image: owncloudci/php:7.1
  commands:
  - ls -la /filesForUpload
  - cp -a /var/www/owncloud/phoenix/tests/acceptance/filesForUpload/. /filesForUpload
  - ls -la /filesForUpload
  volumes:
  - name: uploads
    path: /filesForUpload

- name: webui-acceptance-tests
  pull: always
  image: owncloudci/nodejs:11
  commands:
  - cd /var/www/owncloud/phoenix
  - curl http://phoenix/oidc-callback.html
  - yarn run acceptance-tests-drone
  environment:
    BACKEND_HOST: http://owncloud
    BROWSER_NAME: internet explorer
    SAUCELABS_TUNNEL_NAME: ${DRONE_BUILD_NUMBER}-acceptance-Sharing-IE11
    SAUCE_ACCESS_KEY:
      from_secret: sauce_access_key
    SAUCE_USERNAME:
      from_secret: sauce_username
    SELENIUM_HOST: saucelabs
    SELENIUM_PORT: 4445
    SERVER_HOST: http://phoenix
    TEST_CONTEXT: webUISharing*
    TEST_TAGS: "@smokeTest and not @skip and not @skipOnIE"

services:
- name: phoenix
  pull: always
  image: owncloudci/php:7.1
  commands:
  - mkdir dist
  - /usr/local/bin/apachectl -e debug -D FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/phoenix/dist

- name: owncloud
  pull: always
  image: owncloudci/php:7.1
  command:
  - /usr/local/bin/apachectl
  - -e
  - debug
  - -D
  - FOREGROUND
  environment:
    APACHE_WEBROOT: /var/www/owncloud/server/

- name: saucelabs
  pull: if-not-exists
  image: henrrich/docker-sauce-connect:latest
  commands:
  - /usr/local/sauce-connect/bin/sc -i ${DRONE_BUILD_NUMBER}-acceptance-Sharing-IE11
  environment:
    SAUCE_ACCESS_KEY:
      from_secret: sauce_access_key
    SAUCE_USERNAME:
      from_secret: sauce_username

- name: mysql
  pull: always
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: owncloud
    MYSQL_PASSWORD: owncloud
    MYSQL_ROOT_PASSWORD: owncloud
    MYSQL_USER: owncloud

volumes:
- name: uploads
  temp: {}

trigger:
  ref:
  - refs/tags/**
  - refs/pull/**
  - refs/pull-requests/**
  - refs/merge-requests/**
  - refs/heads/master
  - refs/heads/release*
  - refs/heads/develop*

depends_on:
- lint-test
...
